<a href="https://colab.research.google.com/github/LuxoZppl/herramientasbasicas-zappal-luciano/blob/main/notebooks/An%C3%A1lisis_del_crecimiento_empresarial_%E2%80%94_INC_5000_2019.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introducción

Este proyecto analiza las empresas incluidas en el ranking INC 5000 correspondiente al año 2019.

El objetivo es identificar características y patrones asociados con los niveles de crecimiento de las empresas, considerando variables como industria, ingresos, cantidad de empleados, antigüedad y ubicación geográfica.

El análisis comprende las etapas de carga, limpieza, análisis exploratorio, visualización e interpretación de los datos, y se complementará con un dashboard interactivo desarrollado en Power BI.

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme(style="whitegrid")

pd.set_option("display.max_columns", None)

print("Librerías cargadas correctamente.")

Librerías cargadas correctamente.

In [1]:
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/LuxoZppl/herramientasbasicas-zappal-luciano/main/data/raw/INC5000_limpio%20(1).csv")

print("Dataset cargado correctamente:", df.shape)
display(df.head())

Dataset cargado correctamente: (5012, 17)

,rank,profile,name,url,state,revenue,growth_%,industry,workers,previous_workers,founded,yrs_on_list,metro,city,revenue_millions,company_age_2019,grupo_antiguedad
0,1,https://www.inc.com/profile/freestar,Freestar,http://freestar.com,AZ,36.9 Million,36680.3882,Advertising & Marketing,40.0,5,2015.0,1,Phoenix,Phoenix,36.9,4.0,1–5 años
1,2,https://www.inc.com/profile/freightwise,FreightWise,http://freightwisellc.com,TN,33.6 Million,30547.9317,Logistics & Transportation,39.0,8,2015.0,1,Nashville,Brentwood,33.6,4.0,1–5 años
2,3,https://www.inc.com/profile/ceces-veggie,Cece's Veggie Co.,http://cecesveggieco.com,TX,24.9 Million,23880.4852,Food & Beverage,190.0,10,2015.0,1,Austin,Austin,24.9,4.0,1–5 años
3,4,https://www.inc.com/profile/ladyboss,LadyBoss,http://ladyboss.com,NM,32.4 Million,21849.8925,Consumer Products & Services,57.0,2,2014.0,1,NaN,Albuquerque,32.4,5.0,1–5 años
4,5,https://www.inc.com/profile/perpay,Perpay,http://perpay.com,PA,22.5 Million,18166.4070,Retail,25.0,6,2014.0,1,Philadelphia,Philadelphia,22.5,5.0,1–5 años

In [ ]:
df = pd.read_csv("/content/INC5000_limpio (1).csv")

print("Dataset cargado correctamente:", df.shape)
display(df.head())

Dataset cargado correctamente: (5012, 17)

,rank,profile,name,url,state,revenue,growth_%,industry,workers,previous_workers,founded,yrs_on_list,metro,city,revenue_millions,company_age_2019,grupo_antiguedad
0,1,https://www.inc.com/profile/freestar,Freestar,http://freestar.com,AZ,36.9 Million,36680.3882,Advertising & Marketing,40.0,5,2015.0,1,Phoenix,Phoenix,36.9,4.0,1–5 años
1,2,https://www.inc.com/profile/freightwise,FreightWise,http://freightwisellc.com,TN,33.6 Million,30547.9317,Logistics & Transportation,39.0,8,2015.0,1,Nashville,Brentwood,33.6,4.0,1–5 años
2,3,https://www.inc.com/profile/ceces-veggie,Cece's Veggie Co.,http://cecesveggieco.com,TX,24.9 Million,23880.4852,Food & Beverage,190.0,10,2015.0,1,Austin,Austin,24.9,4.0,1–5 años
3,4,https://www.inc.com/profile/ladyboss,LadyBoss,http://ladyboss.com,NM,32.4 Million,21849.8925,Consumer Products & Services,57.0,2,2014.0,1,NaN,Albuquerque,32.4,5.0,1–5 años
4,5,https://www.inc.com/profile/perpay,Perpay,http://perpay.com,PA,22.5 Million,18166.4070,Retail,25.0,6,2014.0,1,Philadelphia,Philadelphia,22.5,5.0,1–5 años

In [ ]:
print(df.shape)

In [ ]:
print(df.columns.tolist())

In [ ]:
df.head()

In [ ]:
df.tail()

In [ ]:
df.sample(5, random_state=42)

In [ ]:
df.info()

In [ ]:
df.describe()

In [ ]:
df.describe(include="object")

In [ ]:
nulos = df.isna().sum().sort_values(ascending=False)

pct_nulos = (df.isna().mean() * 100).round(2)

tabla_nulos = pd.DataFrame({
    "nulos": nulos,
    "%_nulos": pct_nulos
})

display(tabla_nulos)

In [ ]:
tabla_nulos

In [ ]:
duplicados = df.duplicated().sum()

print(f"Cantidad de filas duplicadas: {duplicados}")

In [ ]:
df["revenue"].head(10)

In [ ]:
df["revenue"].value_counts().head(10)

In [ ]:
df["founded"].value_counts().sort_index().head(20)

In [ ]:
df[df["founded"] == 0]

In [ ]:
df["growth_%"].sort_values(ascending=False).head(10)

In [ ]:
df.sort_values("growth_%", ascending=False).head(10)[
    ["name", "growth_%", "revenue", "industry", "workers", "founded"]
]

In [ ]:
df.sort_values("growth_%", ascending=False).head(10)[
    ["name", "growth_%", "revenue", "industry", "workers", "founded"]
]

In [ ]:
df.sort_values("workers", ascending=False).head(10)[
    ["name", "workers", "previous_workers", "growth_%", "revenue", "industry"]
]

In [ ]:
df["growth_%"].quantile([0.01, 0.25, 0.50, 0.75, 0.99])

In [ ]:
Q1 = df["growth_%"].quantile(0.25)
Q3 = df["growth_%"].quantile(0.75)

IQR = Q3 - Q1

limite_inferior = Q1 - 1.5 * IQR
limite_superior = Q3 + 1.5 * IQR

print(f"Q1: {Q1:.2f}%")
print(f"Q3: {Q3:.2f}%")
print(f"IQR: {IQR:.2f}%")
print(f"Límite inferior: {limite_inferior:.2f}%")
print(f"Límite superior: {limite_superior:.2f}%")

In [ ]:
atipicos_growth = df[df["growth_%"] > limite_superior]

print(f"Cantidad de valores potencialmente atípicos: {len(atipicos_growth)}")
print(f"Porcentaje del dataset: {len(atipicos_growth) / len(df) * 100:.2f}%")

In [ ]:
atipicos_growth[
    ["name", "growth_%", "revenue", "workers", "previous_workers", "industry"]
].sort_values("growth_%", ascending=False).head(20)

In [ ]:
df["workers"].quantile([0.01, 0.25, 0.50, 0.75, 0.99])

In [ ]:
Q1_workers = df["workers"].quantile(0.25)
Q3_workers = df["workers"].quantile(0.75)

IQR_workers = Q3_workers - Q1_workers

limite_superior_workers = Q3_workers + 1.5 * IQR_workers

print(f"Q1: {Q1_workers:.2f}")
print(f"Q3: {Q3_workers:.2f}")
print(f"IQR: {IQR_workers:.2f}")
print(f"Límite superior: {limite_superior_workers:.2f} empleados")

In [ ]:
atipicos_workers = df[df["workers"] > limite_superior_workers]

print(f"Cantidad de empresas: {len(atipicos_workers)}")
print(f"Porcentaje del dataset: {len(atipicos_workers) / len(df) * 100:.2f}%")

In [ ]:
df.isna().sum().sort_values(ascending=False)

In [ ]:
df[df["metro"].isna()][["name", "state", "city", "metro"]].head(20)

In [ ]:
df[df["metro"].isna()]["state"].value_counts().head(15)

In [ ]:
df[df["workers"].isna()][
    ["name", "workers", "previous_workers", "growth_%", "revenue", "industry"]
]

In [ ]:
df[df["founded"] == 0][
    ["name", "founded", "growth_%", "revenue", "industry", "workers"]
]

In [ ]:
df["founded"] = df["founded"].replace(0, np.nan)

In [ ]:
df.isna().sum().sort_values(ascending=False)

In [ ]:
df["revenue"].str.extract(r"(Million|Billion)")[0].value_counts()

In [ ]:
df["revenue_millions"] = (
    df["revenue"]
    .str.replace(" Million", "", regex=False)
    .str.replace(" Billion", "", regex=False)
    .astype(float)
)

df.loc[df["revenue"].str.contains("Billion"), "revenue_millions"] *= 1000

print(df["revenue_millions"].dtype)

In [ ]:
import zipfile
import pandas as pd
import numpy as np

zip_path = "/content/INC+5000+Companies+2019.csv (1).zip"

with zipfile.ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extract("INC 5000 Companies 2019.csv", "/content")

df = pd.read_csv("/content/INC 5000 Companies 2019.csv")

print("Dataset cargado correctamente:", df.shape)

In [ ]:
df["founded"] = df["founded"].replace(0, np.nan)

print("Años de fundación faltantes:", df["founded"].isna().sum())

In [ ]:
df["revenue_millions"] = (
    df["revenue"]
    .str.replace(" Million", "", regex=False)
    .str.replace(" Billion", "", regex=False)
    .astype(float)
)

df.loc[
    df["revenue"].str.contains("Billion"),
    "revenue_millions"
] *= 1000

print("Tipo de dato:", df["revenue_millions"].dtype)
print("Empresas con ingresos en millones:",
      df["revenue"].str.contains("Million").sum())
print("Empresas con ingresos en billones:",
      df["revenue"].str.contains("Billion").sum())

In [ ]:
df[df["revenue"].str.contains("Billion")][
    ["name", "revenue", "revenue_millions"]
].head(10)

In [ ]:
print("Ingresos faltantes:", df["revenue_millions"].isna().sum())
print("Ingresos iguales o menores a cero:",
      (df["revenue_millions"] <= 0).sum())

print("\nResumen estadístico:")
display(df["revenue_millions"].describe())

In [ ]:
print("Nombres duplicados:", df["name"].duplicated().sum())

In [ ]:
print("Cantidad de industrias:", df["industry"].nunique())
print("\nIndustrias disponibles:")
display(df["industry"].value_counts())

In [ ]:
df["industry"] = df["industry"].str.strip()

print("Cantidad de industrias:", df["industry"].nunique())

In [ ]:
print("Posiciones faltantes:", df["rank"].isna().sum())
print("Posiciones duplicadas:", df["rank"].duplicated().sum())
print("Posición mínima:", df["rank"].min())
print("Posición máxima:", df["rank"].max())
print("Cantidad de posiciones únicas:", df["rank"].nunique())

In [ ]:
df[df["rank"].duplicated(keep=False)][
    ["rank", "name", "industry", "growth_%"]
].sort_values("rank")

In [ ]:
ranks_esperados = set(range(1, 5001))
ranks_existentes = set(df["rank"])

faltantes = sorted(ranks_esperados - ranks_existentes)

print("Cantidad de posiciones faltantes:", len(faltantes))
print("Primeras posiciones faltantes:", faltantes[:20])

In [ ]:
print("Empresas con rank 1892:", (df["rank"] == 1892).sum())

print(
    "Cantidad de posiciones repetidas:",
    df["rank"].value_counts().gt(1).sum()
)

In [ ]:
print("Valores faltantes:", df["yrs_on_list"].isna().sum())
print("Valor mínimo:", df["yrs_on_list"].min())
print("Valor máximo:", df["yrs_on_list"].max())
print("Cantidad de valores distintos:", df["yrs_on_list"].nunique())

display(df["yrs_on_list"].value_counts().sort_index())

In [ ]:
print("Valores faltantes:", df["previous_workers"].isna().sum())
print("Valores iguales o menores a cero:", (df["previous_workers"] <= 0).sum())
print("Valor mínimo:", df["previous_workers"].min())
print("Valor máximo:", df["previous_workers"].max())

In [ ]:
print("Valores faltantes:", df["city"].isna().sum())
print("Ciudades distintas:", df["city"].nunique())

df["city"] = df["city"].str.strip()

print("Ciudades distintas después de quitar espacios:",
      df["city"].nunique())

In [ ]:
print("Valores faltantes:", df["state"].isna().sum())
print("Estados distintos:", df["state"].nunique())

df["state"] = df["state"].str.strip()

print("Estados distintos después de quitar espacios:",
      df["state"].nunique())

display(df["state"].value_counts())

In [ ]:
print("Valores faltantes:", df["profile"].isna().sum())
print("Categorías distintas:", df["profile"].nunique())

display(df["profile"].value_counts())

In [ ]:
print("Valores faltantes:", df["url"].isna().sum())
print("URLs distintas:", df["url"].nunique())

display(df[["name", "url", "profile"]].head(10))

In [ ]:
df[[
    "name",
    "workers",
    "previous_workers",
    "growth_%"
]].head(10)

In [ ]:
df["growth_employees_calc"] = (
    (df["workers"] - df["previous_workers"])
    / df["previous_workers"]
) * 100

display(
    df[[
        "name",
        "workers",
        "previous_workers",
        "growth_%",
        "growth_employees_calc"
    ]].head(10)
)

In [ ]:
comparacion = df[["growth_%", "growth_employees_calc"]].corr()

display(comparacion)

In [ ]:
df["change_employees"] = df["workers"] - df["previous_workers"]

print(
    "Correlación con el cambio absoluto de empleados:",
    df["growth_%"].corr(df["change_employees"])
)

In [ ]:
print("Workers faltantes:", df["workers"].isna().sum())
print("Crecimiento de empleados faltante:",
      df["growth_employees_calc"].isna().sum())
print("Cambio de empleados faltante:",
      df["change_employees"].isna().sum())

In [ ]:
print(df.columns.tolist())

In [ ]:
df = df.drop(columns=[
    "growth_employees_calc",
    "change_employees"
])

print("Columnas actuales:", df.shape[1])
print(df.columns.tolist())

In [ ]:
print("Tipo de dato:", df["founded"].dtype)
print("Años faltantes:", df["founded"].isna().sum())
print("Año mínimo:", df["founded"].min())
print("Año máximo:", df["founded"].max())

In [ ]:
display(
    df[[
        "growth_%",
        "revenue_millions",
        "workers",
        "previous_workers",
        "founded",
        "yrs_on_list"
    ]].isna().sum()
)

In [ ]:
resumen_calidad = pd.DataFrame({
    "tipo_dato": df.dtypes.astype(str),
    "valores_faltantes": df.isna().sum(),
    "valores_unicos": df.nunique()
})

display(resumen_calidad)

In [ ]:
print("Categorías vacías:", (df["industry"].str.strip() == "").sum())
print("Valores faltantes:", df["industry"].isna().sum())
print("Cantidad de industrias:", df["industry"].nunique())

In [ ]:
display(
    df["growth_%"].describe(
        percentiles=[0.01, 0.25, 0.50, 0.75, 0.90, 0.95, 0.99]
    )
)

In [ ]:
df.nsmallest(10, "growth_%")[["name", "growth_%", "industry"]]

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme(style="whitegrid")

print("Bibliotecas cargadas correctamente.")

In [ ]:
plt.figure(figsize=(10, 5))

sns.histplot(data=df, x="growth_%", bins=50)

plt.title("Distribución del crecimiento empresarial")
plt.xlabel("Crecimiento (%)")
plt.ylabel("Cantidad de empresas")

plt.show()

In [ ]:
limite_95 = df["growth_%"].quantile(0.95)

plt.figure(figsize=(10, 5))

sns.histplot(
    data=df[df["growth_%"] <= limite_95],
    x="growth_%",
    bins=40
)

plt.title("Distribución del crecimiento empresarial (hasta P95)")
plt.xlabel("Crecimiento (%)")
plt.ylabel("Cantidad de empresas")

plt.show()

In [ ]:
plt.figure(figsize=(10, 4))

sns.boxplot(x=df["growth_%"])

plt.title("Valores atípicos del crecimiento empresarial")
plt.xlabel("Crecimiento (%)")

plt.show()

In [ ]:
crecimiento_industria = (
    df.groupby("industry")["growth_%"]
    .median()
    .sort_values(ascending=False)
    .head(10)
)

plt.figure(figsize=(10, 6))

sns.barplot(
    x=crecimiento_industria.values,
    y=crecimiento_industria.index
)

plt.title("10 industrias con mayor crecimiento mediano")
plt.xlabel("Crecimiento mediano (%)")
plt.ylabel("Industria")

plt.show()

In [ ]:
cantidad_industria = (
    df.groupby("industry")["growth_%"]
    .agg(["count", "median"])
    .sort_values("median", ascending=False)
    .head(10)
)

display(cantidad_industria)

In [ ]:
crecimiento_completo = (
    df.groupby("industry")["growth_%"]
    .median()
    .sort_values()
)

plt.figure(figsize=(10, 8))

sns.barplot(
    x=crecimiento_completo.values,
    y=crecimiento_completo.index
)

plt.title("Crecimiento mediano por industria")
plt.xlabel("Crecimiento mediano (%)")
plt.ylabel("Industria")

plt.show()

In [ ]:
correlacion_ingresos = df["revenue_millions"].corr(df["growth_%"])

print(
    f"Correlación entre ingresos y crecimiento: "
    f"{correlacion_ingresos:.3f}"
)

In [ ]:
correlacion_empleados = df["workers"].corr(df["growth_%"])

print(
    f"Correlación entre empleados y crecimiento: "
    f"{correlacion_empleados:.3f}"
)

In [ ]:
df["company_age_2019"] = 2019 - df["founded"]

print(
    "Correlación entre antigüedad y crecimiento:",
    round(df["company_age_2019"].corr(df["growth_%"]), 3)
)

In [ ]:
plt.figure(figsize=(10, 5))

sns.regplot(
    data=df,
    x="company_age_2019",
    y="growth_%",
    scatter_kws={"alpha": 0.25},
    line_kws={"color": "red"}
)

plt.title("Antigüedad y crecimiento empresarial")
plt.xlabel("Antigüedad en 2019 (años)")
plt.ylabel("Crecimiento (%)")

plt.show()

In [ ]:
df["grupo_antiguedad"] = pd.cut(
    df["company_age_2019"],
    bins=[0, 5, 10, 20, 40, 200],
    labels=[
        "1–5 años",
        "6–10 años",
        "11–20 años",
        "21–40 años",
        "Más de 40 años"
    ]
)

resumen_antiguedad = (
    df.groupby("grupo_antiguedad", observed=False)["growth_%"]
    .agg(["count", "median"])
)

display(resumen_antiguedad)

In [ ]:
plt.figure(figsize=(10, 5))

sns.barplot(
    data=df,
    x="grupo_antiguedad",
    y="growth_%",
    estimator="median",
    errorbar=None
)

plt.title("Crecimiento mediano según antigüedad empresarial")
plt.xlabel("Antigüedad de la empresa en 2019")
plt.ylabel("Crecimiento mediano (%)")

plt.show()

In [ ]:
empresas_estado = (
    df["state"]
    .value_counts()
    .head(10)
)

plt.figure(figsize=(10, 6))

sns.barplot(
    x=empresas_estado.values,
    y=empresas_estado.index
)

plt.title("10 estados con más empresas en el ranking INC 5000")
plt.xlabel("Cantidad de empresas")
plt.ylabel("Estado")

plt.show()

In [ ]:
top_estados = df["state"].value_counts().head(5).index

crecimiento_estado = (
    df[df["state"].isin(top_estados)]
    .groupby("state")["growth_%"]
    .agg(["count", "median"])
    .sort_values("median", ascending=False)
)

display(crecimiento_estado)

In [ ]:
correlacion_tamano_ingresos = df[
    ["workers", "revenue_millions"]
].corr()

display(correlacion_tamano_ingresos)

In [ ]:
plt.figure(figsize=(10, 6))

sns.scatterplot(
    data=df,
    x="workers",
    y="revenue_millions",
    alpha=0.4
)

plt.title("Relación entre cantidad de empleados e ingresos")
plt.xlabel("Cantidad de empleados")
plt.ylabel("Ingresos (millones de USD)")

plt.show()

In [ ]:
limite_workers = df["workers"].quantile(0.95)
limite_revenue = df["revenue_millions"].quantile(0.95)

df_visual = df[
    (df["workers"] <= limite_workers) &
    (df["revenue_millions"] <= limite_revenue)
]

plt.figure(figsize=(10, 6))

sns.scatterplot(
    data=df_visual,
    x="workers",
    y="revenue_millions",
    alpha=0.4
)

plt.title("Empleados e ingresos: empresas hasta el percentil 95")
plt.xlabel("Cantidad de empleados")
plt.ylabel("Ingresos (millones de USD)")

plt.show()

In [ ]:
print("Empresas en el dataset original:", len(df))
print("Empresas mostradas en el gráfico:", len(df_visual))
print("Empresas fuera del gráfico:", len(df) - len(df_visual))
print(
    "Porcentaje mostrado:",
    round(len(df_visual) / len(df) * 100, 2),
    "%"
)

In [ ]:
resumen_ranking = (
    df.groupby("yrs_on_list")["growth_%"]
    .agg(["count", "median"])
    .sort_index()
)

display(resumen_ranking)

In [ ]:
plt.figure(figsize=(10, 5))

sns.lineplot(
    data=resumen_ranking.reset_index(),
    x="yrs_on_list",
    y="median",
    marker="o"
)

plt.title("Crecimiento mediano según años en el ranking")
plt.xlabel("Años en el ranking")
plt.ylabel("Crecimiento mediano (%)")

plt.show()

In [ ]:
print(
    "Correlación entre años en el ranking y crecimiento:",
    round(df["yrs_on_list"].corr(df["growth_%"]), 3)
)

In [ ]:
df["change_employees"] = (
    df["workers"] - df["previous_workers"]
)

display(
    df[
        [
            "name",
            "workers",
            "previous_workers",
            "growth_%",
            "change_employees"
        ]
    ].head(10)
)

In [ ]:
df["growth_employees_calc"] = (
    (df["workers"] - df["previous_workers"])
    / df["previous_workers"]
) * 100

display(
    df[
        [
            "name",
            "workers",
            "previous_workers",
            "growth_%",
            "growth_employees_calc"
        ]
    ].head(10)
)

In [ ]:
display(
    df.sort_values("growth_%", ascending=False)[
        ["name", "growth_%", "revenue", "workers", "previous_workers"]
    ].head(10)
)

### Validación de la variable growth_%

Según la metodología del ranking INC 5000 de 2019, la variable growth_% representa el crecimiento porcentual de los ingresos entre 2015 y 2018.

Por lo tanto, no debe interpretarse como el crecimiento de la cantidad de empleados. La variable workers y previous_workers describen la evolución del personal, mientras que growth_% mide el crecimiento de los ingresos.

Esta distinción es importante para evitar interpretaciones incorrectas y para definir adecuadamente las comparaciones del análisis.

In [ ]:
plt.figure(figsize=(10, 6))

sns.boxplot(
    data=df,
    x="grupo_antiguedad",
    y="growth_%"
)

plt.title("Distribución del crecimiento de ingresos según antigüedad")
plt.xlabel("Antigüedad de la empresa en 2019")
plt.ylabel("Crecimiento de ingresos (%)")
plt.xticks(rotation=20)

plt.show()

In [ ]:
limite_95 = df["growth_%"].quantile(0.95)

plt.figure(figsize=(10, 6))

sns.boxplot(
    data=df,
    x="grupo_antiguedad",
    y="growth_%"
)

plt.ylim(0, limite_95)

plt.title("Crecimiento de ingresos según antigüedad (hasta percentil 95)")
plt.xlabel("Antigüedad de la empresa en 2019")
plt.ylabel("Crecimiento de ingresos (%)")
plt.xticks(rotation=20)

plt.show()

In [ ]:
resumen_industria = (
    df.groupby("industry", observed=True)
    .agg(
        cantidad_empresas=("name", "count"),
        crecimiento_mediano=("growth_%", "median"),
        crecimiento_promedio=("growth_%", "mean")
    )
    .sort_values("crecimiento_mediano", ascending=False)
)

display(resumen_industria.head(10).round(2))

### Interpretación del crecimiento según industria

Retail presenta el mayor crecimiento mediano de ingresos, con un 255,46%, seguido por Media (225,06%) y Energy (215,56%). Software, aunque ocupa el sexto lugar por crecimiento mediano (186,30%), es la industria con mayor cantidad de empresas entre las diez primeras, con 461 registros.

Se observan diferencias importantes entre el crecimiento mediano y el promedio. Por ejemplo, Logistics & Transportation presenta una mediana del 185,25% y un promedio del 717,56%. Esta diferencia sugiere la influencia de valores extremos en el promedio.

Por lo tanto, la mediana resulta una medida útil para comparar industrias sin que unas pocas empresas con crecimientos excepcionalmente altos distorsionen tanto los resultados. Estas diferencias describen asociaciones dentro del ranking analizado y no implican causalidad.

In [ ]:
correlacion = df["workers"].corr(df["revenue_millions"])

print(f"Correlación entre empleados e ingresos: {correlacion:.3f}")

### Interpretación de la relación entre empleados e ingresos

La correlación de Pearson entre la cantidad de empleados y los ingresos es de 0,268, lo que indica una asociación lineal positiva débil. Esto sugiere que las empresas con más empleados tienden a registrar mayores ingresos, aunque la relación presenta una intensidad limitada.

Este resultado no implica que una mayor cantidad de empleados cause mayores ingresos. Además, pueden existir otras características empresariales que ayuden a explicar las diferencias observadas.

In [ ]:
plt.figure(figsize=(10, 6))

sns.scatterplot(
    data=df,
    x="workers",
    y="revenue_millions",
    alpha=0.4
)

plt.title("Relación entre cantidad de empleados e ingresos")
plt.xlabel("Cantidad de empleados")
plt.ylabel("Ingresos (millones de USD)")

plt.show()

In [ ]:
limite_empleados = df["workers"].quantile(0.95)
limite_ingresos = df["revenue_millions"].quantile(0.95)

df_zoom = df[
    (df["workers"] <= limite_empleados) &
    (df["revenue_millions"] <= limite_ingresos)
]

plt.figure(figsize=(10, 6))

sns.scatterplot(
    data=df_zoom,
    x="workers",
    y="revenue_millions",
    alpha=0.4
)

plt.title("Empleados e ingresos: empresas dentro del percentil 95")
plt.xlabel("Cantidad de empleados")
plt.ylabel("Ingresos (millones de USD)")

plt.show()

print(f"Empresas representadas: {len(df_zoom)} de {len(df)}")

### Interpretación de la relación entre empleados e ingresos

El gráfico de dispersión muestra una concentración de empresas con menos de 200 empleados y con ingresos inferiores a 40 millones de USD. Sin embargo, también se observan empresas con ingresos considerablemente mayores dentro de rangos similares de personal.

La correlación de Pearson de 0,268 indica una asociación lineal positiva débil entre ambas variables. Por lo tanto, la cantidad de empleados, por sí sola, no permite explicar completamente las diferencias de ingresos entre las empresas.

Para mejorar la visualización, se representó el 92,44% de las empresas, limitando los valores de ambas variables al percentil 95. Esta decisión afecta únicamente al gráfico y no elimina registros del conjunto de datos original.

In [ ]:
resumen_general = pd.DataFrame({
    "Indicador": [
        "Cantidad de empresas",
        "Cantidad de industrias",
        "Crecimiento mediano de ingresos (%)",
        "Crecimiento promedio de ingresos (%)",
        "Mediana de empleados",
        "Mediana de ingresos (millones USD)",
        "Antigüedad mediana en el ranking (años)"
    ],
    "Valor": [
        df["name"].nunique(),
        df["industry"].nunique(),
        df["growth_%"].median(),
        df["growth_%"].mean(),
        df["workers"].median(),
        df["revenue_millions"].median(),
        df["yrs_on_list"].median()
    ]
})

display(resumen_general.round(2))

### Resumen general de los resultados

El conjunto de datos contiene 5.012 empresas distribuidas en 27 industrias. La empresa representativa según la mediana presenta un crecimiento de ingresos del 157,53%, ingresos por 10,4 millones de USD y 48 empleados. La antigüedad mediana en el ranking es de dos años.

El crecimiento promedio de ingresos alcanza el 454,68%, un valor considerablemente superior a la mediana. Esta diferencia evidencia una distribución asimétrica, influida por empresas con tasas de crecimiento excepcionalmente altas. Por este motivo, la mediana resulta especialmente útil para describir el comportamiento central de las empresas analizadas.

Estos resultados describen las empresas incluidas en el ranking INC 5000 de 2019 y no deben generalizarse automáticamente a todas las empresas.

In [ ]:
import pandas as pd

df = pd.read_csv("/content/INC5000_limpio (1).csv")

print("Dataset cargado:", df.shape)

In [ ]:
print("Filas:", len(df))
print("Columnas:", len(df.columns))
print("Duplicados:", df.duplicated().sum())
print("Valores faltantes:", df.isna().sum().sum())

In [ ]:
print("Filas:", len(df))
print("Columnas:", len(df.columns))
print("Duplicados:", df.duplicated().sum())
print("Valores faltantes:", df.isna().sum().sum())

In [ ]:
faltantes = df.isna().sum()

resumen_faltantes = (
    faltantes[faltantes > 0]
    .sort_values(ascending=False)
    .to_frame(name="Valores faltantes")
)

resumen_faltantes["Porcentaje (%)"] = (
    resumen_faltantes["Valores faltantes"] / len(df) * 100
).round(2)

display(resumen_faltantes)

In [ ]:
import pandas as pd

df = pd.read_csv("/content/INC5000_limpio.csv")

print("Dataset cargado:", df.shape)

In [ ]:

# Eliminar columnas auxiliares de la exploración
df = df.drop(
    columns=["change_employees", "growth_employees_calc"],
    errors="ignore"
)

# Control de calidad final
control_final = pd.DataFrame({
    "Tipo de dato": df.dtypes.astype(str),
    "Valores faltantes": df.isna().sum(),
    "Valores únicos": df.nunique()
})

print("CONTROL DE CALIDAD FINAL")
display(control_final)

print("\nFilas duplicadas:", df.duplicated().sum())
print("Cantidad de filas:", df.shape[0])
print("Cantidad de columnas:", df.shape[1])

In [ ]:
df = df.drop(
    columns=["change_employees", "growth_employees_calc"],
    errors="ignore"
)

print("Columnas después de la limpieza:", df.shape[1])

In [ ]:
print(df.columns.tolist())

### Limpieza y preparación de los datos

El conjunto de datos original contiene 5.012 registros y 14 columnas. Durante la preparación se revisaron los valores faltantes, los registros duplicados, los tipos de datos y los posibles valores extremos.

Se detectaron 813 valores faltantes en la variable `metro`, un valor faltante en `workers` y un valor de `founded` igual a cero, que se consideró inválido y se reemplazó por un valor faltante. No se eliminaron empresas por presentar valores extremos de crecimiento, ya que no se encontró evidencia suficiente para considerarlos errores.

La variable `revenue` se convirtió a un formato numérico expresado en millones de USD para facilitar los cálculos. También se crearon variables derivadas para analizar la antigüedad de las empresas en 2019.

Finalmente, se eliminaron dos columnas auxiliares utilizadas durante la exploración. El conjunto de datos conserva las 5.012 filas originales y no presenta filas completamente duplicadas.

## Conclusiones preliminares

El análisis exploratorio del ranking INC 5000 de 2019 permitió identificar patrones asociados con el crecimiento de los ingresos de las empresas.

En primer lugar, el crecimiento presenta una distribución muy asimétrica: la mediana fue del 157,53%, mientras que el promedio alcanzó el 454,68%. Esto indica que algunas empresas con crecimientos excepcionalmente altos elevan considerablemente el promedio.

En segundo lugar, se observaron diferencias entre industrias. Retail presentó el mayor crecimiento mediano entre las diez industrias analizadas en la tabla comparativa, con un 255,46%, seguida por Media y Energy.

También se encontró una asociación negativa débil entre la antigüedad de las empresas y el crecimiento de sus ingresos. Las empresas de menor antigüedad mostraron medianas de crecimiento más altas dentro de la muestra.

Por último, la cantidad de empleados presentó una asociación lineal positiva débil con los ingresos (correlación de Pearson de 0,268). Esto sugiere que el tamaño de la plantilla, por sí solo, no explica completamente las diferencias de ingresos entre las empresas.

Estos resultados describen asociaciones y patrones observados en el ranking analizado; no permiten establecer relaciones causales ni generalizar automáticamente los resultados a todas las empresas.

In [ ]:
df.to_csv("INC5000_limpio.csv", index=False)

print("Archivo exportado correctamente")

In [ ]:
from google.colab import files
files.download("INC5000_limpio.csv")